pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo wget https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.0-linux-x86_64.tar.gz
    sudo mkdir -p /opt/julia
    sudo tar --strip-components=1 -xzvf julia-1.1.0-linux-x86_64.tar.gz -C /opt/julia
    
    mkdir -p $(HOME)/.julia/dev
    cp -r ${BUILD_SOURCESDIRECTORY} $(HOME)/.julia/dev/ParallelOperations
    
    /opt/julia/bin/julia -e 'using Pkg; pkg"add Distributed"'
    /opt/julia/bin/julia -e 'using Pkg; pkg"develop --local $(HOME)/.julia/dev/ParallelOperations"'
    /opt/julia/bin/julia -e 'using Pkg; pkg"precompile"'
  displayName: 'Install system'
  
- script: |
    /opt/julia/bin/julia -e 'using Pkg; pkg"test ParallelOperations"'
  displayName: 'Run unit-tests'
